version: '3'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .prod.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 7000:7000
    command: pnpm start
    depends on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:17
    .env_file:
      - .prod.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata: /var/lib/postgresql/data
    restart: always

volumes:
  pgdata: